In [3]:
import numpy as np

In [13]:
a = np.arange(10)
np.zeros_like(a)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
b = np.ones_like(a, dtype = int)
print(b)

[1 1 1 1 1 1 1 1 1 1]


In [6]:
c = np.ones(shape=(2,5), dtype = int)
print(c)

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [34]:
d = np.zeros((10,10))
print(d)

print(d.size * d.itemsize,'byte')

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
800 byte


In [39]:
e = np.zeros(10)
e[4] = 1
print(e)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [46]:
f = np.arange(10,51)
print(f)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [50]:
g = np.arange(0,51)
g = g[::-1]
print(g)

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3
  2  1  0]


In [56]:
h = np.arange(1,10).reshape(3,3)
print(h)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [59]:
i = np.nonzero(e)
print(i)

(array([4], dtype=int64),)


In [66]:
a1 = np.array([0,1,2])
a2 = np.array([2,1,0])
a3 = np.array([0,0,0])

ans = np.vstack((a1,a2,a3))
print(ans)

print(np.nonzero(ans))

[[0 1 2]
 [2 1 0]
 [0 0 0]]
(array([0, 0, 1, 1], dtype=int64), array([1, 2, 0, 1], dtype=int64))


In [68]:
a1 = np.arange(0,3)
a2 = np.arange(2,-1,-1)
a3 = np.arange(3)
ans = np.vstack((a1,a2,a3))
print(ans)

print(np.nonzero(ans))

[[0 1 2]
 [2 1 0]
 [0 1 2]]
(array([0, 0, 1, 1, 2, 2], dtype=int64), array([1, 2, 0, 1, 1, 2], dtype=int64))


In [73]:
b1 = np.identity(3)
print(b1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [77]:
a = np.random.random((3,3,3))

print(a)

[[[0.88414241 0.03341649 0.77601914]
  [0.60664664 0.79098638 0.8805173 ]
  [0.42531302 0.84192488 0.06818014]]

 [[0.0231202  0.82265924 0.1759274 ]
  [0.87501337 0.59569871 0.33891958]
  [0.15830895 0.26670669 0.81062255]]

 [[0.41979653 0.17987093 0.00422754]
  [0.21623989 0.12061666 0.04785479]
  [0.31585509 0.86794822 0.70950728]]]


In [83]:
a = np.random.random((5,5))

print(a)
print(a.min())
print(a.max())

[[0.08299073 0.85947141 0.36765497 0.27202867 0.62543308]
 [0.76395262 0.78834313 0.96351312 0.19359305 0.13306768]
 [0.26813898 0.06187426 0.27515572 0.76499873 0.50507232]
 [0.59461785 0.99895668 0.83050194 0.62620107 0.56171782]
 [0.42727322 0.56274617 0.02730858 0.32890569 0.71176737]]
0.027308578709674625
0.9989566771269016


In [89]:
a = np.random.random(50)
print(a)

print(a.sum(), a.mean())

[0.05806471 0.08422225 0.19066078 0.91734459 0.95469166 0.76045003
 0.79226138 0.84577988 0.18042679 0.68116671 0.89267887 0.55252447
 0.07368823 0.24384034 0.30792417 0.27640344 0.06991057 0.10766928
 0.83448206 0.15770938 0.48147402 0.69620762 0.22429831 0.49033375
 0.71495388 0.81082131 0.28540818 0.2853379  0.14726117 0.80648517
 0.90900508 0.42479021 0.08503949 0.20229244 0.7436995  0.79166611
 0.88647998 0.73327182 0.15784883 0.09270341 0.35602182 0.02658903
 0.30641779 0.99736422 0.75968022 0.57529428 0.85844362 0.96683497
 0.42273125 0.91945543]
25.140110418122866 0.5028022083624574


In [95]:
a = np.ones((15,15))
a[1:-1, 1:-1] = 0
print(a)



[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [97]:
a = np.arange(10,51,10)
print(np.pad(a, (2,3), 'constant', constant_values = 0))
print(np.pad(a, (0,3), 'constant', constant_values = 100))

[ 0  0 10 20 30 40 50  0  0  0]
[ 10  20  30  40  50 100 100 100]


In [108]:
a = np.ones((5,5))
print(a)

print(np.pad(a, (1,), constant_values=(0,)))
print(np.pad(a, (2,), constant_values=(0,)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [114]:
a = np.ones((5,5))
print(a)
print()

a[:, [0, -1]] = 0
print(a)
print()

a[[0, -1], :] = 0
print(a)
print()

a = np.ones((5,5))
a[:, [1,-2]] = 0
a[[1, -2]] = 0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]]

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]

[[1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1.]]


In [115]:
0.3 == 3*0.1

False

In [118]:
a = np.diag(range(1,7), k = -1)
print(a)

[[0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 0 0 6 0]]


In [120]:
a = np.tile( np.array([[0.1], [1,0]]), (3,3))
print(a)

[[list([0.1]) list([1, 0]) list([0.1]) list([1, 0]) list([0.1])
  list([1, 0])]
 [list([0.1]) list([1, 0]) list([0.1]) list([1, 0]) list([0.1])
  list([1, 0])]
 [list([0.1]) list([1, 0]) list([0.1]) list([1, 0]) list([0.1])
  list([1, 0])]]


C:\Users\2020A00150\AppData\Local\Temp\ipykernel_13112\3525779625.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.tile( np.array([[0.1], [1,0]]), (3,3))


In [132]:
a = np.arange(11)
print(a)

a[4:8] *= -1
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [135]:
date = np.arange('2030-01','2031-01', dtype = 'datetime64[M]')
print(date)

date1 = np.arange('2001-01', '2031-01', dtype = 'datetime64[Y]')
print(date1)

['2030-01' '2030-02' '2030-03' '2030-04' '2030-05' '2030-06' '2030-07'
 '2030-08' '2030-09' '2030-10' '2030-11' '2030-12']
['2001' '2002' '2003' '2004' '2005' '2006' '2007' '2008' '2009' '2010'
 '2011' '2012' '2013' '2014' '2015' '2016' '2017' '2018' '2019' '2020'
 '2021' '2022' '2023' '2024' '2025' '2026' '2027' '2028' '2029' '2030']


In [144]:
a = np.random.uniform(0,10,100)
print(a.astype(int))

[7 7 4 6 9 9 5 1 2 9 3 4 4 4 0 9 5 3 0 9 8 3 6 5 7 0 0 7 9 4 3 8 1 8 2 0 0
 2 3 9 6 5 1 5 2 0 4 9 3 4 5 4 9 5 3 7 5 4 6 5 8 1 3 2 0 5 1 1 3 0 3 2 3 8
 0 5 4 5 8 5 8 1 6 9 4 2 9 2 4 1 8 1 0 1 5 5 6 1 9 4]


In [146]:
a = np.ones(3)*1
b = np.ones(3)*2
print(a,b)
np.add(a,b,out=a)
print(a)

#divide, negative, add, multiply

[1. 1. 1.] [2. 2. 2.]
[3. 3. 3.]
