In [6]:
import numpy as np

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(-5, 5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [15]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [12]:
np.ones(shape=(5,2), dtype=np.int8)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [13]:
np.zeros(shape=(2,2), dtype=np.float32)

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [14]:
np.empty(shape=(2,4), dtype=np.float32)

array([[-5.8431972e-18,  7.1045832e-43,  8.4489469e-39,  1.0561201e-38],
       [ 1.0469388e-38,  8.4490268e-39,  4.4081739e-39,  4.4081739e-39]],
      dtype=float32)

In [16]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
np.ones_like(x)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [18]:
np.zeros_like(x)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [19]:
np.identity(n=3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [20]:
np.identity(n=4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [21]:
np.eye(N=3, M=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [25]:
np.eye(N=3, M=5, k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [26]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
np.diag(matrix)

array([0, 4, 8])

In [34]:
np.diag(matrix, k=1)

array([1, 5])

In [35]:
np.random.uniform(0,5,10)

array([3.27030426, 0.53030976, 3.75302593, 1.92096904, 2.30202438,
       1.82502639, 2.11464615, 2.90495253, 4.61885115, 1.81179532])

In [36]:
np.random.uniform(0,2,10)

array([0.38292711, 0.47689536, 1.60179794, 0.72853173, 0.0587142 ,
       0.85338065, 0.37879648, 1.08262469, 0.95536031, 0.58391612])

In [40]:
np.arange(1, 200, 2)

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99, 101, 103,
       105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129,
       131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155,
       157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181,
       183, 185, 187, 189, 191, 193, 195, 197, 199])

In [75]:
a = np.arange(1, 200, 2).reshape(10,10)
print(a)

[[  1   3   5   7   9  11  13  15  17  19]
 [ 21  23  25  27  29  31  33  35  37  39]
 [ 41  43  45  47  49  51  53  55  57  59]
 [ 61  63  65  67  69  71  73  75  77  79]
 [ 81  83  85  87  89  91  93  95  97  99]
 [101 103 105 107 109 111 113 115 117 119]
 [121 123 125 127 129 131 133 135 137 139]
 [141 143 145 147 149 151 153 155 157 159]
 [161 163 165 167 169 171 173 175 177 179]
 [181 183 185 187 189 191 193 195 197 199]]


In [69]:
n1 = a[5:8, 0:]
print(n1)

[[101 103 105 107 109 111 113 115 117 119]
 [121 123 125 127 129 131 133 135 137 139]
 [141 143 145 147 149 151 153 155 157 159]]


In [84]:
n2 = a[1::2, 0::2]
print(n2)

[[ 21  25  29  33  37]
 [ 61  65  69  73  77]
 [101 105 109 113 117]
 [141 145 149 153 157]
 [181 185 189 193 197]]


In [86]:
test_array = np.arange(1,11)
test_array.sum()

55

In [87]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [88]:
test_array.sum(axis=0)

array([15, 18, 21, 24])

In [90]:
test_array.sum(axis=1)

array([10, 26, 42])

In [91]:
test_array = np.arange(1,13).reshape(3,4)
third_order_tensor = np.array([test_array,test_array,test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [92]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [93]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [94]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [95]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [96]:
test_array.mean(axis=1)

array([ 2.5,  6.5, 10.5])

In [97]:
test_array.std()

3.452052529534663

In [98]:
test_array.std(axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [99]:
np.sqrt(test_array)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [100]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
np.vstack((v1,v2))

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
np.hstack((v1,v2))

array([1, 2, 3, 4, 5, 6])

In [102]:
v1 = v1.reshape(-1,1)
v2 = v2.reshape(-1,1)
v1

array([[1],
       [2],
       [3]])

In [103]:
v2

array([[4],
       [5],
       [6]])

In [104]:
np.hstack((v1,v2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [106]:
v1 = np.array([[1,2,3]])
v2 = np.array([[4,5,6]])
np.concatenate((v1,v2), axis = 0)

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
v1 = np.array([[1,2,3]])
v2 = np.array([[4,5,6]])
np.concatenate((v1,v2), axis = 1)

array([[1, 2, 3, 4, 5, 6]])

In [109]:
x_1 = np.arange(1,7).reshape(2,3)
x_2 = np.arange(1,7).reshape(3,2)
x_1

array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
x_2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [112]:
x_1.dot(x_2)

array([[22, 28],
       [49, 64]])

In [113]:
A = np.array([[3,22,2]])
B = np.array([[6,7,9],[2,1,3]])